### ISSUE TITLE
Weird graphs with plotgrid() when using implicit_2d() with border_color argument

### ISSUE THREAD

**Issue by Adar70** [Davide-sd/sympy-plot-backends#44] opened 2024-07-05 07:14 UTC
Hello. I'm trying to plot inequalities using `implicit_2d()`. I want the top graph in a column to be all of inequalities at once and bottom graphs to be singular inequalities, each graph for each inequality. However when using the argument `border_color` it doesn't work, progucing more graphs than necessary.
Code that works:
```
import sympy as sp
import spb

x = sp.symbols('x')

ineqs = []
ineqs.append(x + 10 < 3)
ineqs.append(x - 4 > 6)
ineqs.append(x * 5 < 9)

series = []
for ineq in ineqs:
    series += spb.implicit_2d(ineq, rendering_kw = {'alpha':0.5}) #, border_color = 'black'

plots = []
for serie in series:
    plots.append(spb.graphics(serie, show=False))

spb.plotgrid(spb.graphics(*series), *plots)
```
Code that doesn't:
```
import sympy as sp
import spb

x = sp.symbols('x')

ineqs = []
ineqs.append(x + 10 < 3)
ineqs.append(x - 4 > 6)
ineqs.append(x * 5 < 9)

series = []
for ineq in ineqs:
    series += spb.implicit_2d(ineq, border_color = 'black', rendering_kw = {'alpha':0.5}) #

plots = []
for serie in series:
    plots.append(spb.graphics(serie, show=False))

spb.plotgrid(spb.graphics(*series), *plots)
```

I attached pictures of resulting graphs.

Also both codes produce two figures instead of one combined, I don't know why, it's not intended.

![works](https://github.com/Davide-sd/sympy-plot-backends/assets/170083575/c23fe63e-8528-447f-a300-23d71dfab85f)
![not works](https://github.com/Davide-sd/sympy-plot-backends/assets/170083575/f890713c-8f9d-4f40-93c2-7d0393062251)

**Comment by Davide-sd** [comment] 2024-07-08 09:11
Hello @Adar70 ,

[`spb.implicit_2d`](https://sympy-plot-backends.readthedocs.io/en/latest/modules/graphics/functions_2d.html#spb.graphics.functions_2d.implicit_2d) returns a list of up to two `Implicit2DSeries`. Specifically:

1. `spb.implicit_2d(ineq, rendering_kw = {'alpha':0.5})` returns a list with only one  `Implicit2DSeries`, which represents the filled region. In your example you have 3 inequalities, hence `len(series)` will be 3.
2.  `spb.implicit_2d(ineq, rendering_kw = {'alpha':0.5}, border_color = 'black')` returns a list containing two `Implicit2DSeries`, one representing the filled region, and one representing the border. In your example you have 3 inequalities, hence `len(series)` will be 6.

Then, you did this:

```py
plots = []
for serie in series:
    plots.append(spb.graphics(serie, show=False))
```

In the first case, you end up with 3 plots. In the second case you end up with 6 plots.

Finally, you did this:

```py
spb.plotgrid(spb.graphics(*series), *plots)
```

Note the `spb.graphics(*series)`: this is going to create a plot and show it on the the screen, right away. Then, the module processed the rest of the command, creates the plotgrid and shows it on the screen. So you end up with 2 figures.
Instead, you should have asked the first command to not show it on the screen, like this:

```py
spb.plotgrid(spb.graphics(*series, show=False), *plots)
```

This is how I would do it:

```py
import sympy as sp
import spb

x = sp.symbols('x')

ineqs = []
ineqs.append(x + 10 < 3)
ineqs.append(x - 4 > 6)
ineqs.append(x * 5 < 9)

series = []
plots = []
for ineq in ineqs:
    current_series = spb.implicit_2d(ineq, range1=(x, -10, 15), rendering_kw = {'alpha':0.5}, border_color = 'black')
    plots.append(
        spb.graphics(*current_series, show=False)
    )
    series += current_series

spb.plotgrid(spb.graphics(*series, show=False), *plots)
```
![image](https://github.com/Davide-sd/sympy-plot-backends/assets/9921777/8c4a81de-4853-425f-ba49-dcf4e54ffa0e)

Everything is working according to the intended behavior, so I'm closing the issue. But if you need more help, I'm here, just write into this thread.

**Closed by Davide-sd** 2024-07-08 09:11 UTC
